name: "CI"

on:
  push:
    branches:
      - main
      - features/**
    tags:
      - '*.*.*'
  pull_request:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet --info

      - run: ./build.sh

      - if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        name: Publish nuget
        run: dotnet nuget push ./nuget/*.nupkg --source "https://nuget.pkg.github.com/meniga/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
